name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: ''
tag-prefix: ''
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: ''
no-changes-template: '* No changes'
version-template: '$MAJOR.$MINOR.$PATCH$PRERELEASE'
version-resolver:
  major:
    labels: []
  minor:
    labels: []
  patch:
    labels: []
  default: 'patch'
categories: []
exclude-labels: []
include-labels: []
include-paths: []
exclude-contributors: []
no-contributors-template: 'No contributors'
replacers: []
autolabeler: []
sort-by: 'merged_at'
sort-direction: 'descending'
prerelease: false
prerelease-identifier: ''
include-pre-releases: false
latest: 'true'
filter-by-commitish: false
commitish: ''
category-template: '## $TITLE'
header: ''
footer: ''
template: '{{#if nextVersion}}Release {{nextVersion}}{{/if}}'
