#ifndef ING1_PROJET_2021_22_DOFUS_ARENA_EQUIPE_X_1_STATISTIQUES_H
#define ING1_PROJET_2021_22_DOFUS_ARENA_EQUIPE_X_1_STATISTIQUES_H

#include "stdio.h"
#include "../../Structures/structures.h"


#endif //ING1_PROJET_2021_22_DOFUS_ARENA_EQUIPE_X_1_STATISTIQUES_H
