name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: List build directory contents
        run: ls -la build

  generate-release-notes:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release_notes.outputs.tag_name }}
      release_name: ${{ steps.release_notes.outputs.name }}
    steps:
      - name: Generate Release Notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .github/release-drafter.yml

      - name: Set Output Variables
        id: set_outputs
        run: |
          echo "::set-output name=tag_name::${{ steps.release_notes.outputs.tag_name }}"
          echo "::set-output name=release_name::${{ steps.release_notes.outputs.name }}"

  publish:
    needs: generate-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.generate-release-notes.outputs.tag_name }}
          release_name: ${{ needs.generate-release-notes.outputs.release_name }}
          draft: false
          prerelease: false

      - name: List build directory contents for debugging
        run: ls -la build

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/ALBPL  # Update this path as needed
          asset_name: projet-monopoly-ing1
          asset_content_type: application/octet-stream

